

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
      MYSQL_ROOT_PASSWORD: root_password

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    container_name: flask_web_app
    restart: on-failure
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: your_db_name
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    depends_on:
      - db
    
volumes:
  mysql_data:

